sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - node
  - 6
before_install:
  - npm i -g npm@^2.15.1
before_script:
  - npm prune
script:
  - npm run test-travis
after_success:
  - npm install coveralls@2.11.15 && cat ./coverage/lcov.info | coveralls"
env: NODE_ENV=test
