var logger = require('../logger/logger').logger;
var AbstractEnum = require('./abstractEnum').AbstractEnum;

module.exports.MakeEnum = {
  AUDI: 'AUDI',
  ALFA_ROMEO: 'ALFA_ROMEO',
  APRILIA: 'APRILIA',
  BMW: 'BMW',
  BENTLEY: 'BENTLEY',
  BENZHOU: 'BENZHOU',
  BRENDERUP: 'BRENDERUP',
  BORO: 'BORO',
  BAOTIAN: 'BAOTIAN',
  CAN_AM: 'CAN_AM',
  CHEVROLET: 'CHEVROLET',
  CHRYSLER: 'CHRYSLER',
  CITROEN: 'CITROEN',
  COLES: 'COLES',
  CASE_IH: 'CASE_IH',
  DACIA: 'DACIA',
  DAF: 'DAF',
  DAIMLER: 'DAIMLER',
  DAIHATSU: 'DAIHATSU',
  DAEWOO: 'DAEWOO',
  DODGE: 'DODGE',
  FIAT: 'FIAT',
  FERRO: 'FERRO',
  FSO: 'FSO',
  FSM: 'FSM',
  FS_LUBLIN: 'FS_LUBLIN',
  FUXIANDA: 'FUXIANDA',
  FORD: 'FORD',
  GMC: 'GMC',
  GNIOTPOL: 'GNIOTPOL',
  HAOTIAN: 'HAOTIAN',
  HONDA: 'HONDA',
  HUONIAO: 'HUONIAO',
  HYUNDAI: 'HYUNDAI',
  HYOSUNG: 'HYOSUNG',
  IVECO: 'IVECO',
  INTERNATIONAL: 'INTERNATIONAL',
  JAGUAR: 'JAGUAR',
  JAWA: 'JAWA',
  JEEP: 'JEEP',
  JUNAK: 'JUNAK',
  JOHN_DEERE: 'JOHN_DEERE',
  JONWAY: 'JONWAY',
  YAMAHA: 'YAMAHA',
  KANGDA: 'KANGDA',
  KIA: 'KIA',
  KAWASAKI: 'KAWASAKI',
  KYMCO: 'KYMCO',
  KOCH: 'KOCH',
  LANCIA: 'LANCIA',
  LDV: 'LDV',
  LEXUS: 'LEXUS',
  LIAZ: 'LIAZ',
  LAND_ROVER: 'LAND_ROVER',
  LONGJIA: 'LONGJIA',
  MERCEDES: 'MERCEDES',
  MAZDA: 'MAZDA',
  MINI: 'MINI',
  MITSUBISHI: 'MITSUBISHI',
  MAJESTIC_AUTO: 'MAJESTIC_AUTO',
  MG: 'MG',
  MZ: 'MZ',
  MAN: 'MAN',
  NISSAN: 'NISSAN',
  NIEWIADOW: 'NIEWIADOW',
  OGAR: 'OGAR',
  OPEL: 'OPEL',
  PIAGGIO: 'PIAGGIO',
  PEUGEOT: 'PEUGEOT',
  RENAULT: 'RENAULT',
  ROVER: 'ROVER',
  ROLLS_ROYCE: 'ROLLS_ROYCE',
  ROMET_MOTORS: 'ROMET_MOTORS',
  ROUTER: 'ROUTER',
  RIEJU: 'RIEJU',
  SAM: 'SAM',
  SIMSON: 'SIMSON',
  SEAT: 'SEAT',
  SKODA: 'SKODA',
  SETRA: 'SETRA',
  SCANIA: 'SCANIA',
  SCHMITZ_CARGOBULL: 'SCHMITZ_CARGOBULL',
  SPRITE_SPORT: 'SPRITE_SPORT',
  SAAB: 'SAAB',
  SUBARU: 'SUBARU',
  SMART: 'SMART',
  SUZUKI: 'SUZUKI',
  TATA: 'TATA',
  TOROS: 'TOROS',
  TOYOTA: 'TOYOTA',
  TRIUMPH: 'TRIUMPH',
  THULE: 'THULE',
  TEMA: 'TEMA',
  URSUS: 'URSUS',
  UAZ: 'UAZ',
  VOLKSWAGEN: 'VOLKSWAGEN',
  VOLVO: 'VOLVO',
  VAUXHALL: 'VAUXHALL',
  WANGYE: 'WANGYE',
  WAZ: 'WAZ',
  WSK: 'WSK',
  YINMU: 'YINMU',
  YAMASAKI: 'YAMASAKI',
  ZIPP: 'ZIPP',
  UNKNOWN: 'UNKNOWN',

  getMake: function (type, makes) {
    var value = null;

    if (type) {
      type = type.toLowerCase();
      value = AbstractEnum.getValue(type, makes);
    }

    if (value === null) {
      value = 'UNKNOWN';
      logger.warn('MakeEnum.getMake: Unable to get type from "%s" - set "%s" as default', type, value);
    }

    return module.exports.MakeEnum[value];
  }
};
